/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const CardType = t.union(t.lit("Character"), t.lit("Reality"), t.lit("Dream"), t.lit("Boss"));

export const BaseCard = t.iface([], {
  "type": "CardType",
  "name": "string",
  "imageUrl": "string",
  "description": "string",
});

export const Stats = t.iface([], {
  "dice": t.opt(t.union("number", t.lit("lucidity"))),
  "movement": t.opt("number"),
  "memory": t.opt("number"),
  "slumber": t.opt(t.union("number", t.lit("+dice"))),
  "lucidity": t.opt("number"),
  "providence": t.opt(t.union("number", "string")),
});

export const Choice = t.iface([], {
  "description": t.opt("string"),
  "requirement": t.opt("Stats"),
  "success": t.opt("Stats"),
  "failure": t.opt("Stats"),
});

export const CharacterCard = t.iface(["BaseCard"], {
  "type": t.lit("Character"),
  "stats": "Stats",
});

export const RealityCard = t.iface(["BaseCard"], {
  "type": t.lit("Reality"),
  "effect": "Stats",
});

export const DreamCard = t.iface(["BaseCard"], {
  "type": t.lit("Dream"),
  "movement": "number",
  "choices": t.opt(t.array("Choice")),
  "effect": t.opt("Stats"),
});

export const BossCard = t.iface(["BaseCard"], {
  "type": t.lit("Boss"),
});

export const Card = t.union("CharacterCard", "RealityCard", "DreamCard", "BossCard");

export const Cards = t.iface([], {
  "cards": t.array("Card"),
});

const exportedTypeSuite: t.ITypeSuite = {
  CardType,
  BaseCard,
  Stats,
  Choice,
  CharacterCard,
  RealityCard,
  DreamCard,
  BossCard,
  Card,
  Cards,
};
export default exportedTypeSuite;
